export enum actionTypes {
    QUESTIONS_READALL = 'questions/READALL',
    QUESTIONS_GETQUESTIONSFROMAPI = 'questions/QUESTIONS_GETQUESTIONSFROMAPI',
    QUESTIONS_READANSWERSFROMAPI = 'questions/READANSWERSFROMAPI',
    QUESTIONS_SELECTRANDOM = 'question/SELECTRANDOM',
    ANSWER_VALIDATE = 'answer/VALIDATE',
    ANSWER_NEXTQUESTION = 'answer/NEXTQUESTION',
    ANSWER_RETRY = 'answer/RETRY',
}
