export const QUESTIONS_READALL = 'questions/READALL'
export const QUESTIONS_GETQUESTIONSFROMAPI = 'questions/QUESTIONS_GETQUESTIONSFROMAPI'
export const QUESTIONS_READANSWERSFROMAPI = 'questions/READANSWERSFROMAPI'
export const QUESTIONS_SELECTRANDOM = 'question/SELECTRANDOM'