export enum actionTypes {
    QUESTIONS_READALL = 'questions/READALL',
    QUESTIONS_GETQUESTIONSFROMAPI = 'questions/QUESTIONS_GETQUESTIONSFROMAPI',
    QUESTIONS_READANSWERSFROMAPI = 'questions/READANSWERSFROMAPI',
    QUESTIONS_SELECTRANDOM = 'question/SELECTRANDOM',
    QUESTION_VALIDATE = 'question/VALIDATE',
}
